stages:
  - build

build:
  image: php:8.1-cli
  stage: build
  script:
    - apt-get update && apt-get install -y unzip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install --no-interaction --no-ansi --no-scripts
    - composer dump-autoload --no-interaction --no-ansi
  artifacts:
    paths:
      - vendor/
      - composer.lock